### ISSUE TITLE
Question: specification of read length

### ISSUE THREAD

**Issue by ajw2329** [GeorgetteTanner/w-Wessim2#1]
Hello and thanks for the great tool!  I have a quick question: is it possible to specify the read length directly for paired-end output (as opposed to just the fragment length distribution)?  It looks like it is hardcoded to 180 -- am I reading that right?  Would appreciate any help -- thanks!

**Comment by GeorgetteTanner** [comment]
Hello

Thanks for your interest in w-Wessim2. The read lengths are taken from the ReSeq error profiles and so it's not possible to directly specify a read length. But if needed, you could train a new ReSeq error profile using reads of the required length.  
(The 180 in the code just sets a maximum length for when writing the intermediate read sequences, which are then passed to ReSeq and cut down to the correct size based on the Reseq error profiles. I have now changed this to 500 to allow for profiles with longer reads.) 

Hope that helps,
Georgette

**Comment by ajw2329** [comment]
Fantastic thanks very much!!
