### ISSUE TITLE
"imin" no longer defined but still referenced

### ISSUE THREAD

**Issue by ajw2329** [GeorgetteTanner/w-Wessim2#2]
Hello!  Thanks again for your excellent tool. 

On your latest commit, it looks like the fragment length minimum is no longer defined anywhere (it used to be passed as parameter `-m`), but it is still referenced as variable `imin`.  This results in a crash due to (e.g.) line 52:

```
, in main
    print "Fragment:",isize, "+-", isd, ">", imin
NameError: global name 'imin' is not defined
```

**Comment by GeorgetteTanner** [comment]
Hello. Thank you for pointing this out!
I've added a new commit to address the issue and also merged your pull request.

**Comment by ajw2329** [comment]
Fantastic thank you!
