### ISSUE TITLE
Could you add some of the intermediate files to the git repository for debugging purposes?

### ISSUE THREAD

**Issue by JYLeeBioinfo** [GeorgetteTanner/w-Wessim2#4]
Hello, @GeorgetteTanner ! Thank you for making great tool for WES simulation.

Could you help me with an error I faced running the pipeline?

I am stuck at seqToIllumina step with the following error...

```
>>> 30-04-24 00:43:00: info:  Starting read generation
!!! bool reseq::Simulator::ApplyErrorsAndQualityToFastaInput(seqan::StringSet<seqan::String<char, seqan::Alloc<> > >&, seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> > >&, seqan::StringSet<seqan::String<char, seqan::Alloc<> > >&, seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<> > >&, seqan::StringSet<seqan::String<char, seqan::Alloc<> > >&, reseq::Simulator::GeneralRandomDistributions&, std::mt19937_64&, const reseq::DataStats&, const reseq::ProbabilityEstimates&) [/opt/conda/conda-bld/reseq_1645512733196/work/reseq/Simulator.cpp:2431]: error: The two systematic error entries are not separated by a semicolon from themselves or the rest of the ReSeq information: 1 1;478;NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNANNNNNNNNNNGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCANNNNNNNNNNNNNNNNNNNNNNNNNANNNGNTANCANNNNNNNNNNANNNNNNGNNNNNNNNNNCNANTNNNANNNNNCANNGANNNNNCCNNNNNACNAGCNNNNNNNANNNNNNNNNNNNNNNGNNANNNNNNCNNNNCCNNCGNNNNNNNGNNNCNNNNNNNANNNNNNNNNNNNNNNNANNNNNNNNNNNANNNNCNNNN;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!%!!!!!!!!!!*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:A!!!!!!!!!!!!!!!!!!!!!!!!!0!!!'!&+!0*!!!!!!!!!!)!!!!!!?!!!!!!!!!!O!/!)!!!3!!!!!*&!!+-!!!!!5,!!!!!,*!+3&!!!!!!!*!!!!!!!!!!!!!!!'!!3!!!!!!D!!!!%'!!)'!!!!!!!(!!!.!!!!!!!&!!!!!!!!!!!!!!!!P!!!!!!!!!!!)!!!!(!!!!
```

I know I must be very specific about the environments and options I used but they are so complicated that I am afraid I can not clearly explain them to you.

However, if you share the following intermediate files to the git repository,
I will be able to compare the files and find out what is going wrong.

{GENOME}_noNs_syserrors.fq
{GENOME}_w-wessim2_{READNUM}.fa
{GENOME}_w-wessim2_{READNUM}.fq

I suspect that {GENOME}_noNs_syserrors.fq is going wrong on my end. A bunch of Ns are starting to appear from this file...

If you would share those files, it'll be really helpful! Only partial files would be sufficient if the original file is too big.
And I'll also share with you how I resolved the error after successfully figuring things out.

Thank you!

**Comment by hd00ljy** [comment]
I think I found out the potential reason for the error....
There are some entries where the quality score is ";" while reseq detects the format integrity using ";"

![image](https://github.com/GeorgetteTanner/w-Wessim2/assets/13775022/39af2910-958f-485c-9e71-8f6000481615)

**Comment by JYLeeBioinfo** [comment]
I figured out what was the problem.

This is one of records in {GENOME}w-wessim2{READNUM}.fa on my end.
```
>1 1;478;NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNANNNNNNNNNNGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCANNNNNNNNNNNNNNNNNNNNNNNNNANNNGNTANCANNNNNNNNNNANNNNNNGNNNNNNNNNNCNANTNNNANNNNNCANNGANNNNNCCNNNNNACNAGCNNNNNNNANNNNNNNNNNNNNNNGNNANNNNNNCNNNNCCNNCGNNNNNNNGNNNCNNNNNNNANNNNNNNNNNNNNNNNANNNNNNNNNNNANNNNCNNNN;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!%!!!!!!!!!!*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:A!!!!!!!!!!!!!!!!!!!!!!!!!0!!!'!&+!0*!!!!!!!!!!)!!!!!!?!!!!!!!!!!O!/!)!!!3!!!!!*&!!+-!!!!!5,!!!!!,*!+3&!!!!!!!*!!!!!!!!!!!!!!!'!!3!!!!!!D!!!!%'!!)'!!!!!!!(!!!.!!!!!!!&!!!!!!!!!!!!!!!!P!!!!!!!!!!!)!!!!(!!!!
GGATTCGGCGCGCGTGCGGCCCGCCGCGAGTGAGGGTTTTCGTGGTTCACATCCCGCGGCTCACGGGGGAGTGGGCAGCGCCAGGGGCGCCCGCCGCTGTGGCCCTCGTGCTGATGCTACTGAGGAGCCAGCGTCTAGGGCAGCAGCCGCTTCCTAGAAGACCAGGTAGGAAAGGCCCTC
```

The error profile length is much bigger than the actual fragment sequence and the sequence lengths are mostly fixed to 180.

Referring to previous issue #1 , I searched for 180 in the source code and found that 180bp of actual sequence were taken out.

![image](https://github.com/GeorgetteTanner/w-Wessim2/assets/13775022/f99aed1a-99f6-428b-b38c-221cb638e64d)

Since ReSeq checks the integrity of input fasta based on fragment sequence lengths ([source code here](https://github.com/schmeing/ReSeq/blob/053b8d1af635bf0019dc818b3eb0825023abd037/reseq/Simulator.cpp#L2430) ),
if the lengths of error profile and the fragment sequence differ then reseq throws an error that the id row is not delimited by ";".

The error was gone after changing remaining 180 to 500 but I am not sure it is okay to do.
I would appreciate it if you would review this part of your code.

**Comment by GeorgetteTanner** [comment]
Hello
Thank you for your interest in the tool and for looking into the issue. You are right about the 180 and 500 mismatch - the 180 values were left in during the previous commit. That’s now fixed.
That value sets the length for truncating the intermediate sequences being written out, before they're then truncated further by ReSeq to the correct final length. As you pointed out, the base sequence needs to be truncated to the same length as the error profiles.
Let me know if you have anymore issues with it.
Thanks

**Comment by JYLeeBioinfo** [comment]
Thank you for your confirmation!
